FROM openjdk
MAINTAINER Mario Anthony "m.mbinda@spikeassociates.com"
COPY deploy /opt/kafka/consumer
WORKDIR /opt/kafka/consumer
CMD java -cp corebos-1.0-SNAPSHOT-jar-with-dependencies.jar UpdateConsumerExe