FROM openjdk
MAINTAINER Mario Anthony "m.mbinda@spikeassociates.com"
COPY deploy /opt/kafka/producer
WORKDIR /opt/kafka/producer
CMD java -cp corebos-1.0-SNAPSHOT-jar-with-dependencies.jar RESTAPIProducerExe